import { BigNumber, Contract, providers, Wallet } from "ethers";
import {
    provider
} from "./variables"
require('dotenv').config() // lets us use the config in the .env file

// WT_PRIVATE_KEY_1 refers to the private key set up in the .env file
// export const testWallet = new Wallet(process.env.WALLET_PRIVATE_KEY, provider)
export const wallet1 = new Wallet(process.env.WT_PRIVATE_KEY_1, provider)
// export const wallet2 = new Wallet(process.env.WT_PRIVATE_KEY_2, provider)
// export const wallet3 = new Wallet(process.env.WT_PRIVATE_KEY_3, provider)
// export const wallet4 = new Wallet(process.env.WT_PRIVATE_KEY_4, provider)
// export const wallet5 = new Wallet(process.env.WT_PRIVATE_KEY_5, provider)
// export const wallet6 = new Wallet(process.env.WT_PRIVATE_KEY_6, provider)
// export const wallet7 = new Wallet(process.env.WT_PRIVATE_KEY_7, provider)
// export const wallet8 = new Wallet(process.env.WT_PRIVATE_KEY_8, provider)
// export const wallet9 = new Wallet(process.env.WT_PRIVATE_KEY_9, provider)
// export const wallet10 = new Wallet(process.env.WT_PRIVATE_KEY_10, provider)
// export const wallet11 = new Wallet(process.env.WT_PRIVATE_KEY_11, provider)
// export const wallet12 = new Wallet(process.env.WT_PRIVATE_KEY_12, provider)
// export const wallet13 = new Wallet(process.env.WT_PRIVATE_KEY_13, provider)
// export const wallet14 = new Wallet(process.env.WT_PRIVATE_KEY_14, provider)
// export const wallet15 = new Wallet(process.env.WT_PRIVATE_KEY_15, provider)
// export const wallet16 = new Wallet(process.env.WT_PRIVATE_KEY_16, provider)
// export const wallet17 = new Wallet(process.env.WT_PRIVATE_KEY_17, provider)
// export const wallet18 = new Wallet(process.env.WT_PRIVATE_KEY_18, provider)
// export const wallet19 = new Wallet(process.env.WT_PRIVATE_KEY_19, provider)
// export const wallet20 = new Wallet(process.env.WT_PRIVATE_KEY_20, provider)
// export const wallet21 = new Wallet(process.env.WT_PRIVATE_KEY_21, provider)
// export const wallet22 = new Wallet(process.env.WT_PRIVATE_KEY_22, provider)
// export const wallet23 = new Wallet(process.env.WT_PRIVATE_KEY_23, provider)
// export const wallet24 = new Wallet(process.env.WT_PRIVATE_KEY_24, provider)
// export const wallet25 = new Wallet(process.env.WT_PRIVATE_KEY_25, provider)
// export const wallet26 = new Wallet(process.env.WT_PRIVATE_KEY_26, provider)
// export const wallet27 = new Wallet(process.env.WT_PRIVATE_KEY_27, provider)
// export const wallet28 = new Wallet(process.env.WT_PRIVATE_KEY_28, provider)
// export const wallet29 = new Wallet(process.env.WT_PRIVATE_KEY_29, provider)
// export const wallet30 = new Wallet(process.env.WT_PRIVATE_KEY_30, provider)
// export const wallet31 = new Wallet(process.env.WT_PRIVATE_KEY_31, provider)
// export const wallet32 = new Wallet(process.env.WT_PRIVATE_KEY_32, provider)
// export const wallet33 = new Wallet(process.env.WT_PRIVATE_KEY_33, provider)
// export const wallet34 = new Wallet(process.env.WT_PRIVATE_KEY_34, provider)
// export const wallet35 = new Wallet(process.env.WT_PRIVATE_KEY_35, provider)
// export const wallet36 = new Wallet(process.env.WT_PRIVATE_KEY_36, provider)
// export const wallet37 = new Wallet(process.env.WT_PRIVATE_KEY_37, provider)
// export const wallet38 = new Wallet(process.env.WT_PRIVATE_KEY_38, provider)
// export const wallet39 = new Wallet(process.env.WT_PRIVATE_KEY_39, provider)
// export const wallet40 = new Wallet(process.env.WT_PRIVATE_KEY_40, provider)
// export const wallet41 = new Wallet(process.env.WT_PRIVATE_KEY_41, provider)
// export const wallet42 = new Wallet(process.env.WT_PRIVATE_KEY_42, provider)
// export const wallet43 = new Wallet(process.env.WT_PRIVATE_KEY_43, provider)
// export const wallet44 = new Wallet(process.env.WT_PRIVATE_KEY_44, provider)
// export const wallet45 = new Wallet(process.env.WT_PRIVATE_KEY_45, provider)
// export const wallet46 = new Wallet(process.env.WT_PRIVATE_KEY_46, provider)
// export const wallet47 = new Wallet(process.env.WT_PRIVATE_KEY_47, provider)
// export const wallet48 = new Wallet(process.env.WT_PRIVATE_KEY_48, provider)
// export const wallet49 = new Wallet(process.env.WT_PRIVATE_KEY_49, provider)
// export const wallet50 = new Wallet(process.env.WT_PRIVATE_KEY_50, provider)